---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    author: saiteja
    type: proxy
spec:
  replicas: 3
  selector: 
    matchLabels:
      author: saiteja 
      type: proxy
  template:
    metadata: 
      name: nginx-pod
      labels: 
        author: saiteja
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports: 
            - containerPort: 80
              hostPort: 9090
...

