---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: saiteja
spec:
  containers:
    - name: mynginx
      image: nginx

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: guna
                operator: In
                values:
                  - saiteja
...

