---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    author: saiteja
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: a
...
