---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: saiteja
    type: db
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: saiteja
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
...


