---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels:
    name: saiteja
spec:
  replicas: 3
  selector:
    matchLabels:
      name: saiteja
  template: 
    metadata:
      name: postgres-pod
      labels:
        name: saiteja
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  postgres-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: db
...
                        
