---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: httpd-rc
  namespace: test-ns
  labels:
    name: saiteja
    author: sai
spec: 
  replicas: 3
  template: 
    metadata:
      name: httpd-pod
      labels:
        name: saiteja
        author: saiteja
    spec: 
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
...

