---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment
  labels: 
    name: saiteja
spec: 
  replicas: 2
  selector: 
    matchLabels:
      name: saiteja
  template:
    metadata: 
      name: httpd-pod
      labels:
        name: saiteja
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits: 
              cpu: 400m
              memory: 128Mi
...
