---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    name: saiteja
spec: 
  containers: 
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 9090
      resources: 
        requests:
          cpu: 200m
          memory: 64Mi
        limits:  
          cpu: 400m
          memory: 128Mi
...
