apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    name: saiteja
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    author: saiteja
    type: proxy
...
